### ISSUE TITLE
Webstie error on boot up Clean server

### ISSUE THREAD

**Issue by ultra-pool** [EasyX-Community/easyNOMP#180]
```
[2019-10-19T03:47:55.705Z] [info] [system] [Website] : WEBSITE> Website started on 0.0.0.0:80
undefined:3
var out='<style>\r\n\r\n  #bottomNotes {\r\n    display: block;\r\n    padding-left: 18px;\r\n    padding-right: 18px;\r\n    padding-bottom: 18px;\r\n  }\r\n\r\n  #topPool {\r\n    padding-top: 18px;\r\n    padding-left: 18px;\r\n    padding-right: 18px;\r\n  }\r\n\r\n  #topPool>div>div>svg {\r\n    display: block;\r\n    height: 280px;\r\n  }\r\n\r\n  .poolWrapper {\r\n    border: solid 1px #c7c7c7;\r\n    border-radius: 5px;\r\n    padding: 5px;\r\n    margin-bottom: 18px;\r\n  }\r\n\r\n  .poolLabel {\r\n    font-size: 1.2em;\r\n    text-align: center;\r\n    padding: 4px;\r\n  }\r\n\r\n  .poolMinerTable {}\r\n\r\ntable {\r\n    width: 100%;\r\n  }\r\n\r\n/*    kthx css    */\r\n\r\n.vmiddle { vertical-align: middle; }\r\n.vhmiddle { vertical-align: middle; text-align: -webkit-center; }\r\n\r\n.tableHeaderStyle { vertical-align: middle; text-align: -webkit-center; font-size: 14px; color: black; font-size: 16px; color: black; padding: 0 0 0 0; margin: 0 0 0 0; }\r\n.tableRowStyle { vertical-al

TypeError: Cannot read property 'charAt' of undefined
    at Object.eval [as blocks] (eval at doT.template (/user/EasyNOMP/node_modules/dot/doT.js:133:11), <anonymous>:3:2662)
    at processTemplates (/user/EasyNOMP/libs/website.js:89:62)
    at /user/EasyNOMP/libs/website.js:125:13
    at /user/EasyNOMP/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/user/EasyNOMP/node_modules/async/dist/async.js:1064:13)
    at /user/EasyNOMP/node_modules/async/dist/async.js:969:16
    at /user/EasyNOMP/libs/website.js:118:17
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
[2019-10-19T03:47:55.727Z] [error] [system] [init.js] : Master
```
First boot up. Havent touch any of the pages.

**Comment by cryptopool-builders** [comment]
this is because you do not have your config.json, coins/coin.json, or pool_configs/coin.json setup correctly
