### ISSUE TITLE
setting up pool error. ravencoin

### ISSUE THREAD

**Issue by bforemanl** [EasyX-Community/easyNOMP#183]
I am getting the issue when trying to set up new pool:
SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/.nvm/versions/node/v8.1.4/lib/node_modules/npm/lib/npm.js
:9:16)
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run nvm use --delete-prefix v8.1.4 --silent to unset it.

I am not able to run the pool either.

**Comment by mvthul** [comment]
How did u fixed it?
